name: Push Stage version to DockerHub

on:
  push:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Get short SHA
        id: sha
        run: echo "sha_short=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/var_keeper:stage-${{ steps.sha.outputs.sha_short }}
            ${{ secrets.DOCKERHUB_USERNAME }}/var_keeper:stage-latest
